import type { ElementType } from "react"
import { Briefcase, Calculator, Gamepad2, HeartPulse, ListChecks, Music2, PackageCheck, Plane, Radio, Sparkles, Wand2, Zap } from "lucide-react"

export interface PortfolioProject {
  id: number
  title: string
  description: string
  year: string
  link: string
  image: string
  category: string
  icon: ElementType
  relatedIds: number[]
  status: "completed" | "in-progress" | "pending"
  energy: number
}

export const portfolioProjects: PortfolioProject[] = [
  {
    id: 1,
    title: "AmanAsmelash",
    description: "Portfolio home repo and project launcher.",
    year: "2026",
    link: "https://github.com/smba11/AmanAsmelash",
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=1600&auto=format&fit=crop",
    category: "Portfolio",
    icon: Briefcase,
    relatedIds: [2, 8, 11],
    status: "in-progress",
    energy: 96,
  },
  {
    id: 2,
    title: "goatedcalc",
    description: "A compact calculator project with a playful name.",
    year: "2025",
    link: "https://github.com/smba11/goatedcalc",
    image: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?q=80&w=1600&auto=format&fit=crop",
    category: "Utility",
    icon: Calculator,
    relatedIds: [1, 6],
    status: "completed",
    energy: 68,
  },
  {
    id: 3,
    title: "the-imposters-game",
    description: "A social deduction game project built around hidden roles.",
    year: "2025",
    link: "https://github.com/smba11/the-imposters-game",
    image: "https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=1600&auto=format&fit=crop",
    category: "Game",
    icon: Gamepad2,
    relatedIds: [4, 7],
    status: "completed",
    energy: 88,
  },
  {
    id: 4,
    title: "imposter-online",
    description: "A larger online version of an imposter-style game experience.",
    year: "2025",
    link: "https://github.com/smba11/imposter-online",
    image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1600&auto=format&fit=crop",
    category: "Online Game",
    icon: Radio,
    relatedIds: [3, 7, 11],
    status: "in-progress",
    energy: 100,
  },
  {
    id: 5,
    title: "healing-psychotherapy",
    description: "A calm web project for a psychotherapy-focused experience.",
    year: "2025",
    link: "https://github.com/smba11/healing-psychotherapy",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=1600&auto=format&fit=crop",
    category: "Website",
    icon: HeartPulse,
    relatedIds: [1, 10],
    status: "completed",
    energy: 72,
  },
  {
    id: 6,
    title: "trip-packing-helper",
    description: "A practical helper for planning what to bring before a trip.",
    year: "2025",
    link: "https://github.com/smba11/trip-packing-helper",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1600&auto=format&fit=crop",
    category: "Planner",
    icon: Plane,
    relatedIds: [2, 9],
    status: "completed",
    energy: 74,
  },
  {
    id: 7,
    title: "Wiggler",
    description: "A playful project with motion baked into the name.",
    year: "2026",
    link: "https://github.com/smba11/Wiggler",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1600&auto=format&fit=crop",
    category: "Motion",
    icon: Zap,
    relatedIds: [3, 4],
    status: "completed",
    energy: 82,
  },
  {
    id: 8,
    title: "smbaflex",
    description: "A personal-brand project made to show range and style.",
    year: "2026",
    link: "https://github.com/smba11/smbaflex",
    image: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?q=80&w=1600&auto=format&fit=crop",
    category: "Brand",
    icon: Sparkles,
    relatedIds: [1, 12],
    status: "completed",
    energy: 70,
  },
  {
    id: 9,
    title: "linkpass",
    description: "A fresh repo for a link or access-oriented product idea.",
    year: "2026",
    link: "https://github.com/smba11/linkpass",
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1600&auto=format&fit=crop",
    category: "Product",
    icon: PackageCheck,
    relatedIds: [6, 12],
    status: "pending",
    energy: 42,
  },
  {
    id: 10,
    title: "Niechelist",
    description: "A private niche-listing project included in the project map.",
    year: "2026",
    link: "https://github.com/smba11/Niechelist",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1600&auto=format&fit=crop",
    category: "Private",
    icon: ListChecks,
    relatedIds: [5, 12],
    status: "in-progress",
    energy: 64,
  },
  {
    id: 11,
    title: "smbamusic",
    description: "A music-flavored project with creative media potential.",
    year: "2026",
    link: "https://github.com/smba11/smbamusic",
    image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?q=80&w=1600&auto=format&fit=crop",
    category: "Music",
    icon: Music2,
    relatedIds: [1, 4],
    status: "completed",
    energy: 76,
  },
  {
    id: 12,
    title: "Fidel-Labs",
    description: "A lab-style repo for experiments and product ideas.",
    year: "2026",
    link: "https://github.com/smba11/Fidel-Labs",
    image: "https://images.unsplash.com/photo-1535223289827-42f1e9919769?q=80&w=1600&auto=format&fit=crop",
    category: "Lab",
    icon: Wand2,
    relatedIds: [8, 9, 10],
    status: "pending",
    energy: 48,
  },
]
